image: alpine/edge
packages:
  - go
  - mage
sources:
  - https://git.sr.ht/~kiba/gdn
tasks:
  - build: |
      cd gdn
      mage -v build
  - lint: |
      curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.33.0
      PATH="$(go env GOPATH)"/bin:$PATH
      golangci-lint --version
      cd gdn
      mage -v lint
  - test: |
      cd gdn
      mage -v test
